// libs
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
// types
import type { Metadata } from "next";
import { getLocale } from "next-intl/server";
// styles
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary-800 dark:bg-primary-300`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
