// libs
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
// types
import type { Metadata, Viewport } from "next";
import { getLocale } from "next-intl/server";
// styles
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  applicationName: "codebase-nextjs",
  manifest: "/manifest.webmanifest",
  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/icons/icon-192.png", type: "image/png", sizes: "192x192" },
      { url: "/icons/icon-512.png", type: "image/png", sizes: "512x512" },
      { url: "/icons/icon.svg", type: "image/svg+xml", sizes: "any" },
    ],
    apple: [
      // iOS requires PNG apple-touch-icon for proper install icon (no Safari badge)
      { url: "/icons/apple-touch-icon.png", sizes: "180x180" },
    ],
  },
};
export const viewport: Viewport = {
  themeColor: "#78022e",
  viewportFit: "cover",
  width: "100%",
  initialScale: 1,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <meta name="apple-mobile-web-app-title" content="Codebase" />
        <link rel="manifest" href="/manifest.webmanifest" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary-800 dark:bg-primary-300`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
